// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6UxrLNb3bIRom1Qe7G60olQ8D4M3b-xw',
    appId: '1:368734514327:android:eb2f1f1aecdb98d8d08dd2',
    messagingSenderId: '368734514327',
    projectId: 'messchat-ad1cd',
    databaseURL: 'https://messchat-ad1cd-default-rtdb.firebaseio.com',
    storageBucket: 'messchat-ad1cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbK4w3ks5mOk8SpbAwh4JrUF7liVzJ78E',
    appId: '1:368734514327:ios:9f91fa17f7577b9dd08dd2',
    messagingSenderId: '368734514327',
    projectId: 'messchat-ad1cd',
    databaseURL: 'https://messchat-ad1cd-default-rtdb.firebaseio.com',
    storageBucket: 'messchat-ad1cd.appspot.com',
    androidClientId: '368734514327-0ldff9a4npgr67cof1cs5c5gukfpdnj3.apps.googleusercontent.com',
    iosClientId: '368734514327-u9dpjpb3c9m2jnmc54a2vheuvl48fqgt.apps.googleusercontent.com',
    iosBundleId: 'com.example.messApp',
  );
}
